{{- if .Values.engine.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "milvus.engine" . }} 
  labels:
{{ include "milvus.labels" . | indent 4 }}
spec:
{{- if .Values.engine.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.engine.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.engine.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.engine.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: engine
{{- end }}
