gpu:
  enabled: true
  cacheCapacity: 4
  searchResources:
    - gpu0
  buildIndexResources:
    - gpu0

mysql:
  enabled: true
  persistence:
    enabled: false
    storageClass: default
    accessMode: ReadWriteOnce
    size: 5Gi
