apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      paths:
        - /opt/milvus/logs/*.log
      tags: ["milvus"]
      fields_under_root: true
      fields:
        app: milvus
        type: log

    output.logstash:
      hosts: ['ls-logstash.default.svc.cluster.local:5044']
