apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "milvus.fullname" . }}
data:
  server_config.yaml: |
{{ tpl (.Files.Get .Values.mainConf) . | indent 4 }}

  log_config.conf: |
{{ tpl (.Files.Get .Values.logConf) . | indent 4 }}

{{- range $key, $value := .Values.extraConfigFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
