apiVersion: v1
kind: Service
metadata:
  name: {{ template "milvus.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
spec:
{{- if eq .Values.expose.type "clusterIP" }}
{{- $clusterIP := .Values.expose.clusterIP }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ $clusterIP.ports.httpPort }}
      targetPort: {{ .Values.ports.name }}
{{- else if eq .Values.expose.type "nodePort" }}
{{- $nodePort := .Values.expose.nodePort }}
  type: NodePort
  ports:
    - name: http
      port: {{ $nodePort.ports.http.port }}
      targetPort: {{ .Values.ports.name }}
      {{- if $nodePort.ports.http.nodePort }}
      nodePort: {{ $nodePort.ports.http.nodePort }}
      {{- end }}
{{- else if eq .Values.expose.type "loadBalancer" }}
{{- $loadBalancer := .Values.expose.loadBalancer }}
  type: LoadBalancer
  ports:
    - name: http
      port: {{ $loadBalancer.ports.httpPort }}
      targetPort: {{ .Values.ports.name }}
{{- end }}
  selector:
{{ include "milvus.matchLabels" . | indent 4 }}
