persistence:
  enabled: true
  resourcePolicy: ""
  persistentVolumeClaim:
    dbdata:
      existingClaim: ""
      storageClass: "default"
      accessModes: ReadWriteMany
      size: 5Gi
    logfile:
      existingClaim: ""
      storageClass: "default"
      accessModes: ReadWriteMany
      size: 1Gi

mainConf: "ci/config/mysql/cpu/server_config.yaml"

mysql:
  enabled: true
  persistence:
    enabled: false
    storageClass: default
    accessMode: ReadWriteOnce
    size: 5Gi
