persistence:
  enabled: false
  resourcePolicy: ""
  persistentVolumeClaim:
    dbdata:
      existingClaim: ""
      storageClass: "default"
      accessModes: ReadWriteMany
      size: 5Gi
    logfile:
      existingClaim: ""
      storageClass: "default"
      accessModes: ReadWriteMany
      size: 1Gi

mainConf: "ci/config/sqlite/cpu/server_config.yaml"

mysql:
  enabled: false
